const { SiweMessage, generateNonce } = require('siwe');
const jwt = require('jsonwebtoken');
const config = require('../../config');
const { ApiError } = require('../../utils');

// Simple in-memory cache for nonces to prevent replay attacks
// In a production multi-server setup, this should be Redis or a Database
const nonceCache = new Map();

class AuthController {
  /**
   * GET /api/auth/nonce
   * Generates a random nonce for SIWE and stores it temporarily.
   */
  getNonce(req, res) {
    const nonce = generateNonce();
    // Use the user's IP or a temporary session ID as the key
    // For simplicity, we just send it back and expect it in the verification payload
    // Or we can just store the nonce directly as the key to mark it valid
    nonceCache.set(nonce, Date.now());
    
    // Clean up old nonces (older than 10 mins)
    const tenMinsAgo = Date.now() - 10 * 60 * 1000;
    for (const [key, timestamp] of nonceCache.entries()) {
      if (timestamp < tenMinsAgo) {
        nonceCache.delete(key);
      }
    }

    res.json({ success: true, nonce });
  }

  /**
   * POST /api/auth/verify
   * Verifies the SIWE signature and issues a JWT.
   */
  async verifySignature(req, res, next) {
    try {
      const { message, signature } = req.body;

      if (!message || !signature) {
        throw ApiError.badRequest('Message and signature are required');
      }

      const siweMessage = new SiweMessage(message);
      
      // Verify signature against the stored nonce
      const { data: fields } = await siweMessage.verify({
        signature,
      });

      // Optional: check if nonce was generated by us
      if (!nonceCache.has(fields.nonce)) {
        throw ApiError.unauthorized('Invalid or expired nonce');
      }
      
      // Remove used nonce to prevent replay attacks
      nonceCache.delete(fields.nonce);

      // Create JWT token
      const token = jwt.sign(
        { 
          address: fields.address,
          chainId: fields.chainId
        }, 
        config.jwtSecret, 
        { expiresIn: '24h' }
      );

      res.json({
        success: true,
        token,
        address: fields.address
      });
    } catch (error) {
      if (error instanceof ApiError) {
        return next(error);
      }
      return next(ApiError.unauthorized('Invalid signature or message'));
    }
  }
}

module.exports = new AuthController();
