const jwt = require('jsonwebtoken');
const config = require('../../config');
const { ApiError } = require('../../utils');

/**
 * Middleware to verify JWT token generated by SIWE
 */
const requireAuth = (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw ApiError.unauthorized('Authentication token is missing or invalid');
    }

    const token = authHeader.split(' ')[1];
    
    // Verify the JWT token
    const decoded = jwt.verify(token, config.jwtSecret);
    
    // Attach user info to request object
    req.user = {
      address: decoded.address,
      chainId: decoded.chainId
    };

    next();
  } catch (error) {
    if (error.name === 'TokenExpiredError') {
      return next(ApiError.unauthorized('Session has expired. Please sign in again.'));
    }
    return next(ApiError.unauthorized('Invalid authentication token'));
  }
};

module.exports = {
  requireAuth
};
